### ISSUE TITLE
Feature Request - LED lighting control

### ISSUE THREAD

**Issue by droomurray** [BCN3D/BCN3DSigma-Firmware#127]
Add option to menu to set RGB value of lights durning print / include commands to make them controllable in GCODE.

**Comment by flandaluce** [comment]
+1

**Comment by lampi87** [comment]
+1

**Comment by AlejandroGarcia92** [comment]
Hi people, I think that could be awesome but it is not possible to implement it because the only colour that can be controlled by a PWM signal is the Blue. Red and Green only can be controlled with a digital signal.

I've already implemented this gcode to set the value RGB:
```
inline void gcode_M535(){
	int R=0, G=0, B=0;
	if (code_seen('R')) R = (int)code_value();
	if (code_seen('V')) G = (int)code_value();
	if (code_seen('A')) B = (int)code_value();
	
	analogWrite(RED, R);
	analogWrite(GREEN, G);
	analogWrite(BLUE, B);
	
}
```
e.g.: M535 R255 V255 A150

But the only colour that works as analog input is the blue as I said. values range [0-255]
