### ISSUE TITLE
USB connection fails from Cura to Sigma R16 after upgrade to 2.0.2

### ISSUE THREAD

**Issue by SigmaFred** [BCN3D/BCN3DSigma-Firmware#201]
After upgrading Sigma R16 successfully to 2.0.2 using Cura 2.1.0 on MAC, I tried to update now to 2.0.3 but Cura could not connect to Sigma.

Any Idea how to fix this?  

Details: 
Upgraded my Sigma R16 successfully to 2.0.2 using Cura 2.1.0 on MAC
After upgrade (incl. LCD) - did a small test print - looked OK.
Now tried to update now to 2.0.3 but Cura could not connect to Sigma. 
Automatic upgrade failed - tried to use upload 2.0.3 as custom Firmware (see screenshot).
Starts ... but nothing happens ...
Tried same with Windows10 - also not successful. 
Same problem - could not connect to Sigma.

Some observations:
- Sigma is connected with USB cable to Mac. Every time during start of Cura (while 'setting up scene' is shown) the Sigma does a restart (reboot). 
- Setup of Mac and Cura has not changed since I did the upgrade to 2.0.2

![cura](https://user-images.githubusercontent.com/23003780/46312819-7e6bf180-c5c6-11e8-86de-fba15a00dbe4.jpg)

**Comment by AlejandroGarcia92** [comment]
Does Cura detect which FW version have you installed?

**Comment by SigmaFred** [comment]
reopened - sorry for the wrong click

**Comment by AlejandroGarcia92** [comment]
There are a few things that should happen and are not happening. 

- Latest version should appear if you are connected to Internet.

- "Upload custom Firmware" should work anyway.

- Just before, you loaded successfully the firmware and now not.

So, at this point, I'm not able to give you the solution but maybe we would find the problem.

**If the problem comes from CURA:**

Maybe you can try to load the firmware with another version of CURA or a program capable of doing it.

**If the problem comes from Sigma:**

Check the connection or the Port config at PC. (I don't know what to test more)

**Comment by SigmaFred** [comment]
**Got it running finally!**
But with Windows machine only. With my Mac it still does not work.   
Thank you for your advice (and maybe you did a magic spell - without telling me)

Details: 
- Did a restart of Sigma (off/on)
- Shut down my Win Machine
- Started Win machine with Sigma (powered on) plugged in (USB). 
- Checked COM port (on my machine COM3) and changed default 'Baud' from 9600 to 230400.
- Started Cura (2.1.0) - both "current" and "latest version" displayed correctly.
- Then I clicked on "Automatically upgrade ..." and fortunately it worked (btw. with 'rattling' / vibrating motors on Sigma during firmware upload). 
Note: 
- In the meantime I reverted 'Baud' back to 9600 - and it is still working - so no clue if just the change made a difference (or a magic spell of Alejandro)
