### ISSUE TITLE
Measuring Vref on stepper motor driver boards?

### ISSUE THREAD

**Issue by kapetanikolas** [BCN3D/BCN3DSigma-Firmware#53]
Hi, 
I touched the X motors and they are very hot so i just tweaked the on board potensiometers of the stepper driver circuits but want to get an accurate measurement of the current setting. Is there a Vref and if so how can i measure it?

**Comment by kitusmark** [comment]
Hi @kapetanikolas. 

If you disassemble the stepper drivers, be careful with the flat flexible cable. And be careful with shorts because to measure you need to power the printer.

Answering to your question, yes there's a potentiometer to set the maximum current of the coils. You can measure the Vref voltage between the output of the pot and GND. The Current/Voltage ratio is 2. So if you set the pot to 0,5V you'll get 1 Amp of current. 

The output is the top pin and GND is the bottom left pin

![img_2115](https://cloud.githubusercontent.com/assets/6075056/13811348/685f1454-eb75-11e5-83b8-575efb01f1d7.JPG)

Hope it helps. 

We're planning to release some kind of advanced mini-tutorial to tackle these kind of issues.

**Comment by Zorgonaute84** [comment]
Is it a new version of the BCN3D Stepper driver on your picture ? Because mines are green and the setting screws are not in plastic...

**Comment by kitusmark** [comment]
The driver is the same. The only changes are the silkscreen and the potentiometer (same value). The process and the results should be the same.
